### ISSUE TITLE
prom segfaults with psycopg2 2.7.3.1

### ISSUE THREAD

**Issue by Jaymon** [Jaymon/prom#54]
Right now, solution is to drop down to an earlier version:

    $ pip install psycopg2==2.6.2

**Comment by Jaymon** [comment]
> Warning Because the psycopg wheel package uses its own libssl binary, it is incompatible with other extension modules binding with libssl as well, for instance the Python ssl module: the result will likely be a segfault. If you need using both psycopg2 and other libraries using libssl please install psycopg from source. ([via](http://initd.org/psycopg/docs/install.html#binary-install-from-pypi))

[Relevant issue from psycopg2 repo](https://github.com/psycopg/psycopg2/issues/543), not sure why the issue is closes since this seems to be an ongoing problem.

Anyway, the way to get around this is to build psycopg2 from source, this will keep it from using its own bundled libssl:

    $ pip install --no-binary=:all: psycopg2

**Comment by dvarrazzo** [comment]
FYI: you are right that closing the psycopg/psycopg2#543 is not the correct course of action: I will reopen it (I considered it closed as "impossible to fix" and with a documented workaround, but it better stay open).
